apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "service.name" . }}
    service: tbot-sender-service
  name: {{ template "service.fullname" . }}-sender-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "service.name" . }}
        service: tbot-sender-service
    spec:
      containers:
      - image: {{.Values.repository}}:{{.Values.version}}
        name: {{ template "service.fullname" . }}-sender-service
        command: ['node', 'run-tbot-sender.js']
        volumeMounts:
        - name: config
          mountPath: /app/config
          readOnly: true
        - name: certs
          mountPath: /app/config/ssl
          readOnly: true
        env:
        - name: APP_CONF
          value: /app/config/
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: {{.Values.reject_unauthorized | quote }}
      volumes:
      - name: config
        configMap:
          name: {{ template "service.fullname" . }}
      - name: certs
        secret:
          secretName: certificate-{{ template "service.fullname" . }}-sender-service
